### ISSUE TITLE
Switching to alternative ranking

### ISSUE THREAD

**Issue by conradchan** [myblackbeard/basketball-betting-bot#1]
> There's also an alternative ranking that's just looking at the total number of bets you guys got right, and doesn't care about weekly wins if that's more your style.

How do I do this?

**Comment by jojubart** [comment]
You can do this with the **/all_bets** command. 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/23401167/103638077-af2cf500-4f4c-11eb-852f-72f7f852152f.png">


The weekly standings (/standings) are still going be calculated, so at the end of the season there could be different winners for the weekly format and the overall correct bets. 
As such, there's no need to manually switch to some different mode at the moment.
Which of these rankings you choose for selecting the season's winner is up to you.
The bot will display final results for both ranking formats once again at the end of the season and show the winner for both formats.
Is that what you've had in mind?
Just let me know, if there are more features you'd like to see :)

**Comment by conradchan** [comment]
Sounds good, thanks. Enjoying the bot so far.
